<?php
$blockObj= $block->getLayout()->createBlock('Thecon\CustomForms\Block\Oferta');
?>

<h1>Formular Oferta</h1>

<form action="<?php echo $blockObj->getFormAction(); ?>" method="POST" id="form-offer">
    <label for="nume_prenume"><?php echo __('Name'); ?></label>
    <input name="nume_prenume" type="text" required placeholder="<?php echo __('Name'); ?>">

    <label for="telefon"><?php echo __('Phone number'); ?></label>
    <input name="telefon" type="number" required placeholder="<?php echo __('Phone number'); ?>">

    <label for="email"><?php echo __('Email Address'); ?></label>
    <input name="email" type="email" required placeholder="<?php echo __('Email Address'); ?>">

    <label for="mesaj"><?php echo __('Message'); ?></label>
    <textarea rows="4" cols="50" name="mesaj" id="mesaj" form="form-offer"></textarea>

    <button type="submit" class="action" id="submit_filter"><span><?= $block->escapeHtml(__('Send')) ?></span></button>
</form>